# Generated by Django 5.1.3 on 2024-11-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_course_students"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(
                related_name="students_enrolled", to="courses.course"
            ),
        ),
    ]
