# Generated by Django 5.1.3 on 2024-11-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="courses",
        ),
        migrations.AddField(
            model_name="student",
            name="students",
            field=models.ManyToManyField(
                related_name="enrolled_courses", to="students.student"
            ),
        ),
    ]
