# Generated by Django 5.1.3 on 2024-11-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_students"),
        ("students", "0003_remove_student_courses_student_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="students",
        ),
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(to="courses.course"),
        ),
    ]
