# Generated by Django 5.1.3 on 2024-11-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_remove_student_students_student_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="courses",
        ),
    ]
