# Generated by Django 5.1.3 on 2024-11-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_rename_student_courses_student_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
