# Generated by Django 5.1.3 on 2024-11-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_students"),
        ("students", "0005_remove_student_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(related_name="courses", to="students.student"),
        ),
    ]
