# Generated by Django 5.1.3 on 2024-11-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_remove_notification_user"),
        ("students", "0007_rename_student_courses_student_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
    ]
